@BASE_URL = http://localhost:3333
@ACCESS_TOKEN = {{authenticate.response.body.access_token}}

# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "individualRegistration": "56143238800",
  "password": "123456"
}

###

# @name create_user
POST {{BASE_URL}}/accounts
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
  "name": "José Antonio",
  "email": "j.antonio@gmail.com",
  "password": "123456",
  "individualRegistration": "23454276578",
  "cellphone": "11923838482",
  "role": "DELIVERYMAN"
}

###

# @name fetch_delivery_men
GET {{BASE_URL}}/delivery-men
Authorization: Bearer {{ACCESS_TOKEN}}

