version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fast_feet
    volumes:
      - fast_feet_pg_data:/var/lib/postgresql/data

volumes:
  fast_feet_pg_data:
